level_0 = {'node_pos': (110, 400),
           'portal_pos': (100, 400),
           'mushroom_pos': (110, 400),
           'player_pos': (),
           'content': 'this is level 1',
           'unlock': 1,
           'node_graphics': '../graphics/over_world/0',
           'layout': [
    '                                     ',
    '                                     ',
    '                                     ',
    '    P                                ',
    '           XXXX      XXXX            ',
    '                                     ',
    '                                     ',
    'XXXXXXXXX  XXXX   XXXXXXXXXXXXXXXX   ',
    '                                     ',
    '                                     ',
    '                                     ',
]}
level_1 = {'node_pos': (300, 220),
           'player_pos': (0, 200),
           'content': 'this is level 2',
           'unlock': 2,
           'node_graphics': '../graphics/over_world/1',
           'layout': [
    '                                     ',
    '  XXXXXXX        XXX       xxxx      ',
    '           P              xx         ',
    'XXXXX       XXXXXXXX     xxxx        ',
    '  X                                  ',
    '  X        XX          XX            ',
    '  X       XX                         ',
    'XXXXX    X  XXXX    XX  XXXXXXXXXX   ',
    '       X  XXXX    XX  XXXXX          ',
    '    XXXX  XXXXX   XX  XXXX           ',
    'XXXXXXXX  XXXXX   XX  XXXX           ',
]}
level_2 = {'node_pos': (480, 610),
           'player_pos': (),
           'content': 'this is level 3',
           'unlock': 3,
           'node_graphics': '../graphics/over_world/2',
           'layout': [
    '                                     ',
    '  XXXXXXX        XXX       xxxx      ',
    '           P              xx         ',
    'XXXXX       XXXXXXXX     xxxx        ',
    '  X                                  ',
    '  X        XX          XX            ',
    '  X       XX                         ',
    'XXXXX    X  XXXX    XX  XXXXXXXXXX   ',
    '       X  XXXX    XX  XXXXX          ',
    '    XXXX  XXXXX   XX  XXXX           ',
    'XXXXXXXX  XXXXX   XX  XXXX           ',
]}
level_3 = {'node_pos': (610, 350),
           'player_pos': (),
           'content': 'this is level 4',
           'unlock': 4,
           'node_graphics': '../graphics/over_world/3',
           'layout': [
    '                                     ',
    '  XXXXXXX        XXX       xxxx      ',
    '           P              xx         ',
    'XXXXX       XXXXXXXX     xxxx        ',
    '  X                                  ',
    '  X        XX          XX            ',
    '  X       XX                         ',
    'XXXXX    X  XXXX    XX  XXXXXXXXXX   ',
    '       X  XXXX    XX  XXXXX          ',
    '    XXXX  XXXXX   XX  XXXX           ',
    'XXXXXXXX  XXXXX   XX  XXXX           ',
]}
level_4 = {'node_pos': (880, 210),
           'player_pos': (),
           'content': 'this is level 5',
           'unlock': 5,
           'node_graphics': '../graphics/over_world/4',
           'layout': [
    '                                     ',
    '  XXXXXXX        XXX       xxxx      ',
    '           P              xx         ',
    'XXXXX       XXXXXXXX     xxxx        ',
    '  X                                  ',
    '  X        XX          XX            ',
    '  X       XX                         ',
    'XXXXX    X  XXXX    XX  XXXXXXXXXX   ',
    '       X  XXXX    XX  XXXXX          ',
    '    XXXX  XXXXX   XX  XXXX           ',
    'XXXXXXXX  XXXXX   XX  XXXX           ',
]}
level_5 = {'node_pos': (1050, 400),
           'player_pos': (),
           'content': 'this is level 6',
           'unlock': 6,
           'node_graphics': '../graphics/over_world/5',
           'layout': [
    '                                     ',
    '  XXXXXXX        XXX       xxxx      ',
    '           P              xx         ',
    'XXXXX       XXXXXXXX     xxxx        ',
    '  X                                  ',
    '  X        XX          XX            ',
    '  X       XX                         ',
    'XXXXX    X  XXXX    XX  XXXXXXXXXX   ',
    '       X  XXXX    XX  XXXXX          ',
    '    XXXX  XXXXX   XX  XXXX           ',
    'XXXXXXXX  XXXXX   XX  XXXX           ',
]}

levels = {0: level_0,
          1: level_1,
          2: level_2,
          3: level_3,
          4: level_4,
          5: level_5}
